### ISSUE TITLE
On press tab not working IOS only

### ISSUE THREAD

**Issue by ebrahimmelngary** [satya164/react-native-tab-view#1272]
### Current behavior

On press not working when click, swipe only work ios

but android working fine 

### Expected behavior

should press tab working fine

### Reproduction

n

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |   "^3.1.1",

| react-native-pager-view                |  "^5.4.4"
| react-native                           |. "0.64.2",
| expo                                   |cli
| node                                   |
| npm or yarn                            |

**Comment by kessris** [comment]
Not sure if this is related to your case but I had the exact same problem before and it was caused by the z-index. Android was working perfectly fine (both tap + swipe) and swipe worked fine for iOS, but tapping on the tab button didn't work for iOS. I played around with other components on the same level and moving/getting rid of the zIndex field on one of them fixed the issue. But it still didn't make sense after finding out what caused it - I think it's a bug. Anyway, not sure if it's related to your case but thought I'd write it down here in case anyone is in the same situation I was in

**Comment by imdkbj** [comment]
> Not sure if this is related to your case but I had the exact same problem before and it was caused by the z-index. Android was working perfectly fine (both tap + swipe) and swipe worked fine for iOS, but tapping on the tab button didn't work for iOS. I played around with other components on the same level and moving/getting rid of the zIndex field on one of them fixed the issue. But it still didn't make sense after finding out what caused it - I think it's a bug. Anyway, not sure if it's related to your case but thought I'd write it down here in case anyone is in the same situation I was in

Can u pls share the working code of ios.

**Comment by Md-Mudassir47** [comment]
@imdkbj @ebrahimmelngary I too had the exact same issue and i was able to fix it by setting `removeClippedSubviews={false}` under the FlatList component.
